function outcomes=evaluate_security_challenges(outputDir)
%EVALUATE_SECURITY_CHALLENGES Archived 150 voice, including explicit claim 149.
% No recording is enrolled and SkipLogging prevents business/attempt writes.
% These are own-content archive challenges, not targeted impersonation/replay.
root=fileparts(mfilename('fullpath'));
if nargin<1, outputDir=fullfile(root,'Results','security_20260927'); end
if ~isfolder(outputDir), mkdir(outputDir); end
inventory=readtable(fullfile(root,'Results','audit_baseline_20260925', ...
    'inventory_all_paths.csv'),'Delimiter',',','TextType','string','ReadVariableNames',true);
inventory=inventory(string(inventory.FolderLabel)=="2206150",:);
[~,uniqueRows]=unique(inventory.SHA256,'stable');
inventory=inventory(uniqueRows,:);
p=dsp_parameters(); find_best_voice_match('reset');
rows={}; rankingRows={};
for take=1:3
    features=cell(1,2); info=cell(1,2); queryPaths=strings(1,2);
    for ph=1:2
        phrases=["ID","Name"];
        candidates=inventory(inventory.Phrase==phrases(ph),:);
        chosen=[];
        for n=1:height(candidates)
            [~,base]=fileparts(candidates.Path(n));
            if strcmp(base,num2str(take)), chosen=n; break; end
        end
        assert(~isempty(chosen),'security:missingChallenge','Historical challenge is unavailable.');
        queryPaths(ph)=candidates.Path(chosen);
        assert(isfile(queryPaths(ph)),'security:missingAudio','Missing archived WAV: %s',queryPaths(ph));
        features{ph}=enrol_template_features(queryPaths(ph),[],p);
        folders={p.trainIdFolder,p.trainNameFolder};
        [~,~,info{ph}]=find_best_voice_match(folders{ph},features{ph},p);
        [scores,order]=sort(info{ph}.Scores);
        for rank=1:min(5,numel(order))
            rankingRows(end+1,:)={"2206150",take,phrases(ph),rank, ...
                info{ph}.Users(order(rank)),scores(rank),queryPaths(ph)}; %#ok<AGROW>
        end
    end
    claims=unique([string(info{1}.Users(:));"2206150"],'stable');
    for claim=claims'
        result=verify_meal_workflow([], '',p,struct('ClaimedID',char(claim), ...
            'IDFeatures',features{1},'NameFeatures',features{2},'SkipLogging',true));
        rows(end+1,:)={"2206150",claim,take,string(info{1}.BestUser), ...
            string(info{2}.BestUser),info{1}.BestDistance,info{2}.BestDistance, ...
            info{1}.Margin,info{2}.Margin,result.Verified,result.Granted, ...
            string(result.Stage),string(result.Decision),string(result.Reason),result.NameCaptured,string(result.IdentifiedBy), ...
            queryPaths(1),queryPaths(2), ...
            "Historical own-content archive pair; folder label only; not the unsaved live incident"}; %#ok<AGROW>
    end
end
outcomes=cell2table(rows,'VariableNames',{'ActualStudent','ClaimedStudent','Take', ...
    'IDCandidate','NameCandidate','IDDistance','NameDistance','IDMargin','NameMargin', ...
    'Verified','Granted','Stage','Decision','Reason','NameCaptured','IdentifiedBy','IDPath','NamePath','Evidence'});
rankings=cell2table(rankingRows,'VariableNames', ...
    {'ActualStudent','Take','Phrase','Rank','Candidate','Distance','Path'});
writetable(outcomes,fullfile(outputDir,'challenge_claims.csv'));
writetable(rankings,fullfile(outputDir,'challenge_top5.csv'));
target=outcomes(outcomes.ClaimedStudent=="2206149",:);
summary=struct('RecordedAt',char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')), ...
    'TargetClaim','2206149','ActualFolderLabel','2206150', ...
    'TargetAttempts',height(target),'TargetFalseAccepts',sum(target.Verified), ...
    'AllClaims',height(outcomes),'AllClaimAccepts',sum(outcomes.Verified), ...
    'RecordSeconds',p.recordDur,'ProcessingFs',p.processingFs, ...
    'CaptureMode','Automatic speech end with eight-second cap','MaxVerificationAttempts',p.maxVerificationAttempts, ...
    'SpeechStop',p.speechStop, ...
    'ProfileRoot',p.trainBaseFolder,'EnrollmentTemplateFileNames',{p.enrollmentTemplateFileNames}, ...
    'Variant',p.voiceCalibration.Variant,'FrontEnd',p.featureFrontEnd, ...
    'Protocol',p.voiceCalibration.Protocol, ...
    'Threshold',p.dtwThreshold,'MarginRatio',p.dtwMarginRatio, ...
    'IDThreshold',field(p,'idDtwThreshold',p.dtwThreshold), ...
    'NameThreshold',field(p,'nameDtwThreshold',p.dtwThreshold), ...
    'IDMargin',field(p,'idMarginRatio',p.dtwMarginRatio), ...
    'NameMargin',field(p,'nameMarginRatio',p.dtwMarginRatio), ...
    'Evidence','Historical own-content challenges against active enrollment including 150. Candidate/distance columns are independent diagnostics; NameCaptured marks workflow usage. No targeted impersonation or labeled replay set.');
file=fopen(fullfile(outputDir,'deployment_summary.json'),'w');
assert(file>=0); clean=onCleanup(@()fclose(file)); %#ok<NASGU>
fprintf(file,'%s\n',jsonencode(summary,'PrettyPrint',true));
assert(height(target)==3 && ~any(target.Granted),'security:falseAcceptance', ...
    'At least one archived 150 pair was accepted under claim 149. Inspect challenge_claims.csv.');
disp('HISTORICAL_FALSE_CLAIM_CHECK_PASS');
end

function value=field(s,key,fallback)
value=fallback;
if isfield(s,key), value=s.(key); end
end
