function result = manual_entry_workflow(student, typedCode, params, nowValue, skipLogging) %#ok<INUSD>
%MANUAL_ENTRY_WORKFLOW Refuse the retired typed-ID-only meal access path.
% A payment record or coupon proves entitlement, not speaker identity. Keep
% the result contract for old callers, but never record payment or a meal.
% Original source: ../preservation/continuation_2026-09-27_before/manual_entry_workflow.m.
if nargin < 1, student = ''; end
[student, ~] = student_id_contract(student);
result = struct('Granted', false, 'Verified', false, ...
    'Decision', 'REJECTED / RETRY', 'Student', student, 'StudentName', '', ...
    'Stage', 'manual-disabled', ...
    'Reason', ['Manual-only entry cannot verify identity. Run run_meal_system ' ...
        'and complete Student ID and full-name voice verification.'], ...
    'Meal', '', 'Logged', false, 'LogMessage', '', ...
    'NameDistance', NaN, 'CouponDistance', NaN, 'Margin', NaN, ...
    'Method', 'ManualFallbackDisabled', 'IdentifiedBy', '');
end
