function summary = test_current_system()
%TEST_CURRENT_SYSTEM Current supported regression suite; temporary stores only.
% Historical coupon-success and ID-only tests describe retired policies.
suites={'test_security_consistency','test_speaker_verification', ...
    'test_verification_sequence','test_admin_monthly_roster_gui', ...
    'test_legacy_entry_points','test_gui_stop_controls','test_voice_calibration', ...
    'test_meal_evidence_log','test_speech_capture_state','test_dsp_options'};
results=runtests(suites);
assertSuccess(results);
assert(test_monthly_roster_backend());
assert(test_coupon_retirement());
test_project_improvement_report();
summary=struct('UnitTestsPassed',sum([results.Passed]), ...
    'UnitTestsFailed',sum([results.Failed]), ...
    'AdditionalChecks',{{'monthly roster backend','coupon retirement','evidence arithmetic'}});
fprintf('CURRENT SYSTEM: %d unit tests passed plus roster, retirement and evidence checks.\n', ...
    summary.UnitTestsPassed);
end
